### ISSUE TITLE
Include passport in package.json

### ISSUE THREAD

**Issue by mohsenSy** [taskment/taskment#20]
Hi, I tried to install your application by following these steps

```
git clone git@github.com:taskment/taskment.git
cd taskment
cp .env.example .env # I filled .env with right database connection information
composer install
php artisan migrate --seed
php artisan passport:install
```

The last command gives this error

```
There are no commands defined in the "passport" namespace.
```

I checked your `package.json` file and did not find and `passport` dependencies.

If I try to serve your application using this command `php artisan serve` and access it using a browser I get this error

```
Facade\Ignition\Exceptions\ViewException
The Mix manifest does not exist. (View: /home/mouhsen/src/github/taskment/resources/views/app.blade.php)
```

How can I get this up and running??

**Comment by mohsenSy** [comment]
@zainaldeen

**Comment by zainaldeen** [comment]
> @zainaldeen

First of all thanks for your interest,
By the name of Taskment members we are all glade that you tried to install our project,
Unfortionatlly lately we decied to make our project close source so we move it to gitlab to make it private 

But about your question we haven't use passport authentication 
You can try to write instead :

> composer require laravel/ui:^2.4
> php artisan ui vue --auth 

Even that we will glade to meet you and discuse our project with such legend like you 😁

**Comment by zainaldeen** [comment]
In addition to be sure that you need to use npm install to install node-modules like this:

> npm install

> npm run watch
